version: 0.1.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015 RC
configuration: Release
platform:
- x86
- x64
install:
- ps: $env:Path = "C:\Program Files (x86)\MSBuild\14.0\Bin;" + $ENV:PATH
- ps: . .\bootstrap.ps1
test_script:
- ps: .\$ENV:CONFIGURATION\$ENV:PLATFORM\run.exe
