version: 0.1.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015 RC
configuration: Release
platform:
- x86
- x64
install:
- ps: $env:Path = "C:\Program Files (x86)\MSBuild\14.0\Bin;" + $ENV:PATH
- ps: . .\bootstrap.ps1
build:
  project: mssql.sln   
test_script:
- ps: Invoke-Expression .\$ENV:CONFIGURATION\test.exe
