version: 0.1.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015 RC
configuration: Release
platform:
- x86
- x64
services:
  - mssql2014
install:
- ps: $env:Path = "C:\Program Files (x86)\MSBuild\14.0\Bin;" + $ENV:PATH
- ps: .\bootstrap.ps1
build:
  project: mssql.sln   
test_script:
- ps: $sqlInstance = "(local)\SQL2014"
- ps: $sqlUser = "sa"
- ps: $sqlPw = "Password12!"
- ps: sqlcmd -S "$sqlInstance" -i .\test\test.sql
- ps: $ENV:MSSQL_CONNECTION_STRING = "Driver={SQL Server Native Client 11.0};Server=$sqlInstance;Database=mapnik_tmp_mssql_db;Uid=$sqlUser;Pwd=$sqlPw;"
- ps: .\test.ps1
